//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwytto.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KStr() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kwytto.Localization.KStr", typeof(KStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Item.
        /// </summary>
        public static string comm_addItemList {
            get {
                return ResourceManager.GetString("comm_addItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extra informations.
        /// </summary>
        public static string comm_betaExtraInfo {
            get {
                return ResourceManager.GetString("comm_betaExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connected to mod.
        /// </summary>
        public static string comm_connectionSection_asConnected {
            get {
                return ResourceManager.GetString("comm_connectionSection_asConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disconnected/Standalone.
        /// </summary>
        public static string comm_connectionSection_asFallback {
            get {
                return ResourceManager.GetString("comm_connectionSection_asFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custom implementation ({0}; p={1}).
        /// </summary>
        public static string comm_connectionSection_connectedCustom {
            get {
                return ResourceManager.GetString("comm_connectionSection_connectedCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default connection on.
        /// </summary>
        public static string comm_connectionSection_connectedDefault {
            get {
                return ResourceManager.GetString("comm_connectionSection_connectedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Loading mode not supported.
        /// </summary>
        public static string comm_connectionSection_invalidMode {
            get {
                return ResourceManager.GetString("comm_connectionSection_invalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not connected.
        /// </summary>
        public static string comm_connectionSection_notConnected {
            get {
                return ResourceManager.GetString("comm_connectionSection_notConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mod Connections.
        /// </summary>
        public static string comm_connectionsSection_title {
            get {
                return ResourceManager.GetString("comm_connectionsSection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current version: &lt;color yellow&gt;{0}&lt;/color&gt;.
        /// </summary>
        public static string comm_currentVersionFormat {
            get {
                return ResourceManager.GetString("comm_currentVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Debug mode.
        /// </summary>
        public static string comm_debugMode {
            get {
                return ResourceManager.GetString("comm_debugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E.
        /// </summary>
        public static string comm_Enum__Cardinal16_E {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENE.
        /// </summary>
        public static string comm_Enum__Cardinal16_ENE {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_ENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ESE.
        /// </summary>
        public static string comm_Enum__Cardinal16_ESE {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_ESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N.
        /// </summary>
        public static string comm_Enum__Cardinal16_N {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NE.
        /// </summary>
        public static string comm_Enum__Cardinal16_NE {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NNE.
        /// </summary>
        public static string comm_Enum__Cardinal16_NNE {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_NNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NNW.
        /// </summary>
        public static string comm_Enum__Cardinal16_NNW {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_NNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NW.
        /// </summary>
        public static string comm_Enum__Cardinal16_NW {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a S.
        /// </summary>
        public static string comm_Enum__Cardinal16_S {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SE.
        /// </summary>
        public static string comm_Enum__Cardinal16_SE {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SSE.
        /// </summary>
        public static string comm_Enum__Cardinal16_SSE {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_SSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SSW.
        /// </summary>
        public static string comm_Enum__Cardinal16_SSW {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_SSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SW.
        /// </summary>
        public static string comm_Enum__Cardinal16_SW {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a W.
        /// </summary>
        public static string comm_Enum__Cardinal16_W {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WNW.
        /// </summary>
        public static string comm_Enum__Cardinal16_WNW {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_WNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WSW.
        /// </summary>
        public static string comm_Enum__Cardinal16_WSW {
            get {
                return ResourceManager.GetString("comm_Enum__Cardinal16_WSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred while loading the data from &lt;color=yellow&gt;{0}&lt;/color&gt;..
        /// </summary>
        public static string comm_errLoadingDataWindow_Header {
            get {
                return ResourceManager.GetString("comm_errLoadingDataWindow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Raw data:.
        /// </summary>
        public static string comm_errLoadingDataWindow_HeaderRawData {
            get {
                return ResourceManager.GetString("comm_errLoadingDataWindow_HeaderRawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please open a issue in GitHub along with the game log attached and a printscreen of this window to get this checked by the mod developer. See the &lt;color=cyan&gt;Report-a-bug Helper&lt;/color&gt; button in the mod options menu to see details about how to get the game log..
        /// </summary>
        public static string comm_errLoadingDataWindow_HeaderReportABug {
            get {
                return ResourceManager.GetString("comm_errLoadingDataWindow_HeaderReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error loading &apos;{0}&apos; data.
        /// </summary>
        public static string comm_errLoadingDataWindow_Title {
            get {
                return ResourceManager.GetString("comm_errLoadingDataWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error!.
        /// </summary>
        public static string comm_errorTitle {
            get {
                return ResourceManager.GetString("comm_errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go to file location.
        /// </summary>
        public static string comm_goToFileLocation {
            get {
                return ResourceManager.GetString("comm_goToFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mod UI Font.
        /// </summary>
        public static string comm_modUiFont {
            get {
                return ResourceManager.GetString("comm_modUiFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a See release notes.
        /// </summary>
        public static string comm_releaseNotes {
            get {
                return ResourceManager.GetString("comm_releaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current Version:.
        /// </summary>
        public static string comm_releaseNotes_CurrentVersion {
            get {
                return ResourceManager.GetString("comm_releaseNotes_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Follow Kwytto at Twitter to get update news!.
        /// </summary>
        public static string comm_releaseNotes_FollowKwytto {
            get {
                return ResourceManager.GetString("comm_releaseNotes_FollowKwytto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Okay!.
        /// </summary>
        public static string comm_releaseNotes_Ok {
            get {
                return ResourceManager.GetString("comm_releaseNotes_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a See news at Workshop Page!.
        /// </summary>
        public static string comm_releaseNotes_ToWorkshop {
            get {
                return ResourceManager.GetString("comm_releaseNotes_ToWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} was updated! Release notes:.
        /// </summary>
        public static string comm_releaseNotes_WasUpdatedTitle {
            get {
                return ResourceManager.GetString("comm_releaseNotes_WasUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report-a-bug helper.
        /// </summary>
        public static string comm_reportABugBtn {
            get {
                return ResourceManager.GetString("comm_reportABugBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If you find any problem with this mod, please send me the output_log.txt (or player.log on Mac/Linux) in the mod Workshop page. If applies, a printscreen can help too to make a better guess about what is happening wrong here...
        ///Additionally, you can find the mod log at the leftmost button below.
        ///
        ///There&apos;s a link for a Workshop guide by &lt;color=#008800&gt;aubergine18&lt;/color&gt; explaining how to find your log file, depending of OS you&apos;re using.
        ///Feel free to create a topic at Workshop or just leave a comment link [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string comm_reportABugContent {
            get {
                return ResourceManager.GetString("comm_reportABugContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go to the guide.
        /// </summary>
        public static string comm_reportABugOpt_GoToGuide {
            get {
                return ResourceManager.GetString("comm_reportABugOpt_GoToGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go to mod log.
        /// </summary>
        public static string comm_reportABugOpt_GoToModLog {
            get {
                return ResourceManager.GetString("comm_reportABugOpt_GoToModLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go to mod page.
        /// </summary>
        public static string comm_reportABugOpt_GoToModPage {
            get {
                return ResourceManager.GetString("comm_reportABugOpt_GoToModPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Okay....
        /// </summary>
        public static string comm_reportABugOpt_Ok {
            get {
                return ResourceManager.GetString("comm_reportABugOpt_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Same as Game&gt;.
        /// </summary>
        public static string comm_sameAsGameFont {
            get {
                return ResourceManager.GetString("comm_sameAsGameFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UI Background Opacity (when in game).
        /// </summary>
        public static string comm_uiOpacity {
            get {
                return ResourceManager.GetString("comm_uiOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UI Scale.
        /// </summary>
        public static string comm_uiScale {
            get {
                return ResourceManager.GetString("comm_uiScale", resourceCulture);
            }
        }
    }
}
